### PR TITLE
Add go.mod and go.sum

### PR DESCRIPTION
**Pull request by jcmuller**

### CODE REVIEW

**Comment by milosgajdos** [comment]
With Go modules being [on by default from 1.16](https://go-review.googlesource.com/c/go/+/255052) adding the modules support into this project would be an awesome cherry on a cake.

**Review by Uzume — APPROVED** [review]

**Comment by der-eismann** [comment]
@dmitshur Would you mind merging this? This would make tracking dependencies so much easier.

**Comment by ajschmidt8** [comment]
@dmitshur, any updates here? Is this project still maintained?

Merging this PR would be very helpful.

**Comment by marco-m** [comment]
Since now the githubv4 module has a `go.mod` file, it seems that this PR can be closed ?

**Comment by dmitshur** [comment]
Thanks. Closing.

**Pull request closed without merging**
